// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5ikRygFEJh-M2WqI6juZ1K6EFx72aoU4',
    appId: '1:1019215471075:web:b7a622678f789cdf6d40d6',
    messagingSenderId: '1019215471075',
    projectId: 'ayitikonekt',
    authDomain: 'ayitikonekt.firebaseapp.com',
    storageBucket: 'ayitikonekt.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqDhAve58Yjx358a5K2MJWXJzW5qS63po',
    appId: '1:1019215471075:android:730716eccc1d30736d40d6',
    messagingSenderId: '1019215471075',
    projectId: 'ayitikonekt',
    storageBucket: 'ayitikonekt.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDYCN7iyABjfN7_bMrAYXR_NZ-M8Ab3Ko',
    appId: '1:1019215471075:ios:58f16ea4248209796d40d6',
    messagingSenderId: '1019215471075',
    projectId: 'ayitikonekt',
    storageBucket: 'ayitikonekt.firebasestorage.app',
    iosBundleId: 'com.example.ayitikonektApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDYCN7iyABjfN7_bMrAYXR_NZ-M8Ab3Ko',
    appId: '1:1019215471075:ios:58f16ea4248209796d40d6',
    messagingSenderId: '1019215471075',
    projectId: 'ayitikonekt',
    storageBucket: 'ayitikonekt.firebasestorage.app',
    iosBundleId: 'com.example.ayitikonektApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5ikRygFEJh-M2WqI6juZ1K6EFx72aoU4',
    appId: '1:1019215471075:web:b42b983daebc53c76d40d6',
    messagingSenderId: '1019215471075',
    projectId: 'ayitikonekt',
    authDomain: 'ayitikonekt.firebaseapp.com',
    storageBucket: 'ayitikonekt.firebasestorage.app',
  );
}
